### ISSUE TITLE
How to use remark/rehype plugins with it?

### ISSUE THREAD

**Issue by tfsomrat** [natemoo-re/astro-remote#8]
Thanks for creating this awesome package for Astro. I just want to know how can I use remark or rehype plugins with this package? Like `next-mdx-remote` has API's for this. https://github.com/hashicorp/next-mdx-remote#apis

can you please help me with that?

**Comment by JulianCataldo** [comment]
Hello,
sharing my POV on this:
This lib is made to be fast and thus, opininated. It's not modular by design, like the unified extensive eco-system.
`unified` tools are flexible and powerful, but slower (more moving parts…). Although I didn't made measurements.
Also this lib is tailored for Astro's JSX runtime magics (SSR components injection), it brings some MDX-likes capabilities to regular Markdown, like a components maps provider.
So `astro-remote` is more used for real-time, SSR-ed markdown transformations.

Alternatively you can use Astro's built-ins remark / mdx / … engine, or build your own custom pipeline with unified (at the risk of re-inventing the wheel). You could also totally use this lib and unified in tandem.

cheers
